# Generated by Django 5.0.1 on 2024-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimage', models.ImageField(upload_to='static/uploads/')),
                ('ctitle', models.CharField(max_length=100)),
                ('cdiscription', models.CharField(max_length=200)),
            ],
        ),
    ]
