# Generated by Django 5.0.1 on 2024-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_homeservicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheading', models.CharField(max_length=100)),
                ('stitle', models.CharField(max_length=100)),
                ('sdetails', models.CharField(max_length=300)),
            ],
        ),
    ]
