# Generated by Django 5.0.1 on 2024-02-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_serviceaboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srvimage', models.ImageField(upload_to='static/uploads/')),
                ('srvtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
