# Generated by Django 5.0.1 on 2024-02-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_servicecardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnimage', models.ImageField(upload_to='static/uploads/')),
                ('trncount', models.CharField(max_length=100)),
                ('trntitle', models.CharField(max_length=100)),
            ],
        ),
    ]
