# Generated by Django 5.0.1 on 2024-02-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardimg', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
