# Generated by Django 5.0.1 on 2024-02-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_awardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmimage', models.ImageField(upload_to='static/uploads/')),
                ('tmname', models.CharField(max_length=100)),
                ('tmposition', models.CharField(max_length=100)),
            ],
        ),
    ]
