# Generated by Django 5.0.1 on 2024-02-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_teammembermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimage', models.ImageField(upload_to='static/uploads/')),
                ('btitle', models.CharField(max_length=100)),
                ('bdetails', models.CharField(max_length=1000)),
                ('bby', models.CharField(max_length=100)),
            ],
        ),
    ]
